; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;------Environment Config------
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit ADS1X15@^2.5.0	;Adafruit ADS1X15
	coryjfowler/mcp_can@^1.5.1			;Cory J Fowler's MCP CAN
	autowp/autowp-mcp2515@^1.2.1		;AutoWP MCP2515

;------Sensor Config------
;Sensor 1
;[env:node1]
upload_port = COM7

;Sensor 2
;[env:node2]
;upload_port = COM8

;To flash code, use 'pio run -e node1 -t upload' and again w/ node2
;To monitor, use 'pio device monitor -p COM7 (or COM8, whichever is receiver)'